blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/edit/<int:pk>/', views.post_edit, name='post_edit'),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='автор'
    )
    title = models.CharField('заголовок', max_length=222)
    text = models.TextField('содержимое')
    created_date = models.DateTimeField('дата создания', default=timezone.now)
    published_date = models.DateTimeField('дата публикации', blank=True, null=True)

    class Meta:
        verbose_name = 'новость'
        verbose_name_plural = 'новости'

    def get_title_with_author(self):
        title = str(self.title)
        first_name = getattr(self.author, 'first_name')
        last_name = getattr(self.author, 'last_name')
        if first_name:
            if last_name:
                return f'{title} (автор: {last_name} {first_name})'
            return f'{title} (автор: {first_name})'
        return title

    title_with_author = property(
        fget=get_title_with_author,
        doc='Заголовок с указанием автора.'
    )

    def get_is_cut(self):
        return getattr(self.text, 'count')('\n') != 0

    is_cut = property(
        fget=get_is_cut,
        doc='Сокращенный текст.'
    )

    def get_cut(self):
        return getattr(self.text, 'splitlines')()[0]

    cut = property(
        fget=get_cut,
        doc='Сокращенный текст.'
    )

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text')

blog/views.py
from django.contrib.auth.models import User, AnonymousUser
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseForbidden
from django.utils import timezone
from .forms import PostForm
from .models import Post


def post_list(request):
    if isinstance(request.user, AnonymousUser):
        request_user = User.objects.get(username='guest')
    else:
        request_user = request.user
    posts = (
        getattr(Post, 'objects').filter(
            published_date__lte=timezone.now()
        ).order_by('-published_date')
    )
    return render(
        request, 'blog/posts.html',
        {
            'posts': posts,
            'request_user': request_user
        }
    )


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})


def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            if isinstance(request.user, AnonymousUser):
                post.author = User.objects.get(username='guest')
            else:
                post.author = request.user
            post.publish()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_new.html', {'form': form})


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if isinstance(request.user, AnonymousUser):
        request_user = User.objects.get(username='guest')
    else:
        request_user = request.user
    if request_user != post.author:
        raise HttpResponseForbidden
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request_user
            post.publish()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

blog/templates/blog/master.html
{% extends "gto/master.html" %}
{% load static %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'blog/css/main.css' %}">
{% endblock extra_head %}

blog/templates/blog/post_detail.html
{% extends "blog/master.html" %}
{% block title %}Новость сайта ГТО{% endblock %}
{% block content %}
  <div class="row">
    <div class="col">
      <article class="blog-post">
        {% if post.published_date %}
        <time class="blog-post-date">
          {{ post.published_date }}
        </time>
        {% endif %}
        <h1>{{ post.title_with_author }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
      </article>
    </div>
  </div>
{% endblock content %}

blog/templates/blog/post_edit.html
{% extends "blog/master.html" %}
{% block title %}ГТО - отредактировать новость{% endblock %}
{% block content %}
<div class="row">
  <div class="col">
    <h1>Редактирование поста</h1>
    <form method="POST" class="blog-post-form">
      {% csrf_token %}
      {{ form.as_p }}
      <button
              type="submit"
              class="btn btn-secondary blog-post-form-save">
        Сохранить
      </button>
    </form>
  </div>
</div>
{% endblock content %}

blog/templates/blog/post_new.html
{% extends "blog/master.html" %}
{% block title %}ГТО - добавление новости{% endblock %}
{% block content %}
<div class="row">
  <div class="col">
    <h1>Новый пост</h1>
    <form method="POST" class="blog-post-form">
      {% csrf_token %}
      {{ form.as_p }}
      <button
              type="submit"
              class="btn btn-secondary blog-post-form-save">
        Сохранить
      </button>
    </form>
  </div>
</div>
{% endblock content %}

blog/templates/blog/posts.html
{% extends "blog/master.html" %}
{% block title %}Комплекс «Готов к труду и обороне» (ГТО){% endblock %}
{% block content %}
    <div class="row">
        <div class="col">
        {% for post in posts %}
        <article class="blog-post">
            {% if post.author == request_user %}
            <aside class="blog-post-actions" style="margin-left: 10px">
                <a
                    class="btn btn-secondary"
                    href="{% url 'blog:post_edit' pk=post.pk %}">
                {% include './svg/pencil-fill.svg' %}
                </a>
            </aside>
            {% endif %}
            {% if post.published_date %}
            <time class="blog-post-date">{{ post.published_date }}</time>
            {% endif %}
            <h1 class="blog-post-heading">
                {{ post.title_with_author }}
            </h1>
            {% if post.is_cut %}
            <p>
                {{ post.cut }}
                <a href="{% url 'blog:post_detail' pk=post.pk %}">Читать далее...</a>
            </p>
            {% else %}
            <p>{{ post.text }}</p>
            {% endif %}
        </article>
        {% endfor %}
        </div>
    </div>
{% endblock content %}